<a href="https://colab.research.google.com/github/HanJeongGyu/abcd/blob/main/abcd20240516.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Pooling example
input_example = torch.tensor([[[0, 1.0, 2],[3, 4, 5], [6, 7, 8]]])
print(input_example)

# Max pooling
max_pooling_layer = nn.MaxPool2d(kernel_size=2, stride=1)
print(max_pooling_layer)
print(max_pooling_layer(input_example))

# Average pooling
average_pooling_layer = nn.AvgPool2d(kernel_size=2, stride=1)
print(average_pooling_layer)
print(average_pooling_layer(input_example))

tensor([[[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]])
MaxPool2d(kernel_size=2, stride=1, padding=0, dilation=1, ceil_mode=False)
tensor([[[4., 5.],
         [7., 8.]]])
AvgPool2d(kernel_size=2, stride=1, padding=0)
tensor([[[2., 3.],
         [5., 6.]]])


In [7]:
import torch
import torch.nn as nn
import torch.nn.functional as F

input_example = torch.tensor([[[12,20,30,0.0],[20,12,2,0],[0,70,5,2]]])
print(input_example)

max_pooling_layer = nn.MaxPool2d(kernel_size=2, stride=2)
print('\nmax pooling:\n', max_pooling_layer(input_example))

average_pooling_layer = torch.nn.AvgPool2d(kernel_size=2, stride=2)
print('\naverage pooling:\n', average_pooling_layer(input_example))


tensor([[[12., 20., 30.,  0.],
         [20., 12.,  2.,  0.],
         [ 0., 70.,  5.,  2.]]])

max pooling:
 tensor([[[20., 30.]]])

average pooling:
 tensor([[[16.,  8.]]])


In [10]:
import torch.nn as nn

conv1 = nn.Conv2d(in_channels=1, out_channels=32, kernel_size=3, padding=1)

print(conv1)

Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [11]:
import torch.nn as nn

conv2 = nn.Conv2d(in_channels=32, out_channels=64, kernel_size=3, padding=1)

print(conv2)

Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F

pool = nn.MaxPool2d(kernel_size=2)

print(pool)

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)


NameError: name 'inputs' is not defined

In [25]:
import torch
import torch.nn as nn
import torch.nn.functional as F

inputs = torch.Tensor(1, 1, 32, 32)
out = conv1(inputs)
print(out.shape)

torch.Size([1, 32, 32, 32])


In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F

out =

SyntaxError: invalid syntax (<ipython-input-23-3e09a3012f4a>, line 5)

In [26]:
#10
inputs = torch.Tensor(1,1,32,32)

inputs.shape

torch.Size([1, 1, 32, 32])

tenserflow 예제

In [ ]:
import tensorflow as if
from tensorflow.keras.layers import Input,Dense,Flatten
from tensorflow.keras.models import Model

height = 28
width = 28
channels = 3 #RGB

input_layer = input(shape = (height, width, channels)) #입력층에 shape 설정

flatten_layer= Flatten()(input_layer) #이미지 데이터 1차원 벡터로 펼치기